config/routes.rb
Rails.application.routes.draw do

  devise_for :owners, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :stores do
    resources :goals do
      resources :daily_goals
    end
  end

  root to: "stores#index"
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  month      :integer
#  beginning  :date
#  ending     :date
#  amount     :decimal(, )
#  store_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_goals_on_store_id  (store_id)
#

class Goal < ApplicationRecord
  belongs_to :store, required: true

  has_many :daily_goals

  validates :month, presence: true
  validates :beginning, presence: true
  validates :ending, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :beginning, :ending, :overlap => {:scope => :store_id}

  after_save :create_daily_goals

  default_scope -> {includes(:daily_goals).order(:beginning)}

  def create_daily_goals
    daily_goals.destroy_all if daily_goals.any?
    (beginning..ending).each do |day|
      DailyGoal.new(day: day, goal: self).save(:validate => false)
    end
  end

  def month_to_s
    "#{I18n.t("date.month_names")[month]} / #{year}"
  end

  def year
    beginning.year
  end

end

app/controllers/goals_controller.rb
class GoalsController < AppController
  belongs_to :store

  protected
    def goal_params
      params.require(:goal).permit(:month, :beginning, :ending, :amount).merge(store: @store)
    end
end

app/views/goals/_form.slim
= simple_form_for([@store, resource]) do |f|
  = f.error_notification
  .row
    .form-inputs.col-md-3
      = f.input :month, collection: (1..12).to_a.map{|i| [t("date.month_names")[i], i]}, include_blank: false
    .form-inputs.col-md-3
      = f.input :beginning, as: :string, input_html: { value: f.object.beginning, class: "date_picker"   }
    .form-inputs.col-md-3
      = f.input :ending, as: :string, input_html: { value: f.object.ending, class: "date_picker" }
    .form-inputs.col-md-3
      = f.input :amount, as: :string, input_html: { value: number_to_currency(f.object.amount), class:"money", maxlength: 15, placeholder: "R$: 0,00"}
  .row.col-md-12
    = f.button :submit_cancel, 'Save', cancel: :back

app/views/goals/edit.slim
= render 'form'

app/views/goals/index.slim
= search_form_for [@store, @q] do |f|
  = link_to new_resource_url, class: 'btn btn-success' do
    = icon(:plus)
    |
    = t('helpers.links.new')

- if self.respond_to?(:collection) && collection.length.nonzero?
  p.pull-right= page_entries_info collection, entry_name: 'item'

  table.table
    - collection.each do |resource|
      thead
        tr
          th= resource_class.human_attribute_name(:month)
          th= resource_class.human_attribute_name(:beginning)
          th= resource_class.human_attribute_name(:ending)
          th= resource_class.human_attribute_name(:amonth)
          th.pull-right.actions= t('helpers.actions')
      tbody
          tr
            td= resource.month_to_s
            td= l resource.beginning
            td= l resource.ending
            td= number_to_currency(resource.amount)
            th.pull-right.actions
              = link_to edit_resource_url(resource), class: 'btn btn-warning', title: t('helpers.links.edit') do
                = icon(:pencil)
              |
              = link_to resource_url(resource), class: 'btn btn-danger', title: t('helpers.links.destroy'), method: :delete do
                = icon('trash-o')
          thead
            tr
              th
                |
              th= DailyGoal.human_attribute_name(:day)
              th= DailyGoal.human_attribute_name(:amount)
              th= DailyGoal.human_attribute_name(:sellers)
              th.pull-right.actions= t('helpers.actions')
          - resource.daily_goals.each do |daily_goal|
            tr
              td
                |
              td= l daily_goal.day
              td= number_to_currency(daily_goal.amount)
              td= daily_goal.amount_per_seller_to_s(number_to_currency(daily_goal.amount_per_seller))
              th.pull-right.actions
                = link_to edit_store_goal_daily_goal_path(@store, resource.id, daily_goal.id), remote: true, class: 'btn btn-warning', title: t('helpers.links.edit') do
                  = icon(:pencil)
  = paginate collection
- else
  br
  .callout.callout-info.lead
    h4= t('helpers.page_entries_info.nobody', model: resource_class.model_name.human)

#dailyGoalModal.modal.fade aria-labelledby="dailyGoalModalLabel" role="dialog"

app/views/goals/new.slim
= render 'form'

app/views/goals/show.slim
- form_params.each do |field|
  - next if field.is_a? Hash
  p
    = label_tag field
    | : 
    = resource.public_send(field)
  
= link_to collection_path, class: 'btn btn-default' do 
  = icon('mail-reply')
  |  
  = t("helpers.links.back")
  