config/routes.rb
Rails.application.routes.draw do

  devise_for :owners, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :stores do
    resources :goals do
      resources :daily_goals
    end
  end

  root to: "stores#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html
  before_action :authenticate_owner!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :get_owner_stores, if: :current_owner

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    end

    def get_owner_stores
      @owner_stores ||= current_owner.stores.where.not(id: 0)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_active(name)
    (controller_name == name) ? 'active' : ''
  end

  def menu_link(name, icon_name)
      content_tag(:li, class: menu_active(name)) do
        link_to(public_send(name + '_path'), 'data-turbolinks-action' => "replace") {
          icon(icon_name) + content_tag(:span, t(name.singularize, scope: 'activerecord.models').pluralize)
        }
      end
  end
end

app/views/application/_footer.slim
footer.main-footer
  .pull-right.hidden-xs
    |  Anything you want
  strong
    | Copyright © 2016 -
    = Date.current.year.to_s+" "
    a[href="#"]
      | Company
    | .
  |  All rights reserved.

app/views/application/_right_side_bar.slim
aside.control-sidebar.control-sidebar-dark
  ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
    li.active
      a[href="#control-sidebar-home-tab" data-toggle="tab"]
        i.fa.fa-home
    li
      a[href="#control-sidebar-settings-tab" data-toggle="tab"]
        i.fa.fa-gears
        
  .tab-content
    #control-sidebar-home-tab.tab-pane.active
      h3.control-sidebar-heading
        | Recent Activity
      ul.control-sidebar-menu
        li
          a[href="javascript:;"]
            i.menu-icon.fa.fa-birthday-cake.bg-red
            .menu-info
              h4.control-sidebar-subheading
                | Langdon's Birthday
              p
                | Will be 23 on April 24th
      h3.control-sidebar-heading
        | Tasks Progress
      ul.control-sidebar-menu
        li
          a[href="javascript:;"]

            h4.control-sidebar-subheading
              |  Custom Template Design
              span.pull-right-container
                span.label.label-danger.pull-right
                  | 70%
            .progress.progress-xxs
              .progress-bar.progress-bar-danger[style="width: 70%"]
    #control-sidebar-stats-tab.tab-pane
      | Stats Tab Content
    #control-sidebar-settings-tab.tab-pane
      form[method="post"]
        h3.control-sidebar-heading
          | General Settings
        .form-group
          label.control-sidebar-subheading
            |  Report panel usage
            input.pull-right[type="checkbox" checked]
          p
            |  Some information about this general settings option
            
.control-sidebar-bg

app/views/application/_side_bar.slim
aside.main-sidebar
  section.sidebar
    .user-panel
      .pull-left.image
        = image_tag('user.png', class: :'img-circle', alt: 'User Image')
      .pull-left.info
        p
          = current_owner.email
        a[href="#"]
          i.fa.fa-circle.text-success
          |  Online
    form.sidebar-form[action="#" method="get"]
      .input-group
        input.form-control[type="text" name="q" placeholder="Search..."]
        span.input-group-btn
          button#search-btn.btn.btn-flat[type="submit" name="search"]
            i.fa.fa-search
    ul.sidebar-menu
      li.header
        | Menu
      = menu_link('stores','building-o')
      li.treeview
        a[href="#"]
          i.fa.fa-line-chart
          span
            = t("goal", scope: 'activerecord.models', count:2)
          span.pull-right-container
            i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          - @owner_stores.each do |store|
            li
              = link_to store.name, store_goals_path(store)

app/views/application/_top_bar.slim
header.main-header
  =link_to :root, class: "logo"
    span.logo-mini
      b
        | D.
      | idv
    span.logo-lg
      b
        | Desafio Indeva
  nav.navbar.navbar-static-top[role="navigation"]
    a.sidebar-toggle[href="#side-bar" data-toggle="offcanvas" role="button"]
      span.sr-only
        | Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        //li.dropdown.messages-menu
          a.dropdown-toggle[href="#messages" data-toggle="dropdown"]
            i.fa.fa-envelope-o
            span.label.label-success
              | 4
          ul.dropdown-menu
            li.header
              | You have 4 messages
            li
              ul.menu
                li
                  a[href="#"]

                  .pull-left
                    = image_tag('user', class: :'img-circle', alt: 'User Image')
                  h4
                    |  Support Team
                    small
                      i.fa.fa-clock-o
                      |  5 mins
                  p
                    | Why not buy a new awesome theme?
            li.footer
              a[href="#"]
                | See All Messages
        //li.dropdown.notifications-menu
          a.dropdown-toggle[href="#notifications" data-toggle="dropdown"]
            i.fa.fa-bell-o
            span.label.label-warning data-behavior='notifications-unread-count'
              | 0
          ul.dropdown-menu
            li.header
              | You have
              span data-behavior='notifications-unread-count' 0
              |  notifications
            li
              ul.menu data-behavior='notification-items'
                / li
                  a[href="#"]
                    i.fa.fa-users.text-aqua
                    |  5 new members joined today
            li.footer
              a[href="#"]
                | View all
              a[href="#" data-behavior='notifications-mark_all_read']
                | Marke All Read
        //li.dropdown.tasks-menu
          a.dropdown-toggle[href="#tasks" data-toggle="dropdown"]
            i.fa.fa-flag-o
            span.label.label-danger
              | 9
          ul.dropdown-menu
            li.header
              | You have 9 tasks
            li
              ul.menu
                li
                  a[href="#"]

                  h3
                    |  Design some buttons
                    small.pull-right
                      | 20%
                  .progress.xs
                    .progress-bar.progress-bar-aqua[style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"]
                      span.sr-only
                        | 20% Complete
            li.footer
              a[href="#"]
                | View all tasks
        li.dropdown.user.user-menu
          a.dropdown-toggle[href="#profile" data-toggle="dropdown"]
            = image_tag('user.png', class: :'user-image', alt: 'User Image')
            span.hidden-xs
              = (current_owner.try(:name) || current_owner.email) + " "
              = icon("caret-down")
          ul.dropdown-menu
            li.user-header
              = image_tag('user.png', class: :'img-circle', alt: 'User Image')
              p data-id=current_owner.id
                = current_owner.email
                //small
                  | Foo bar
            //li.user-body
              .row
                .col-xs-4.text-center
                  a[href="#"]
                    | Followers
                .col-xs-4.text-center
                  a[href="#"]
                    | Sales
                .col-xs-4.text-center
                  a[href="#"]
                    | Friends
            li.user-footer
              .pull-left
                //= link_to('Perfil', edit_user_path(current_owner), class:"btn btn-default btn-flat")
              .pull-right
                = link_to('Sair'.html_safe, destroy_owner_session_path, method: 'delete', class: 'btn btn-default btn-flat')
        //li
          a[href="#right-side-bar" data-toggle="control-sidebar"]
            i.fa.fa-gears